#!/bin/bash
set -euxo pipefail

debug-message "Reticulating Splines..."

# patch a random deployment to use a low memory limit & request

app_slug=$(agent variable get APP_SLUG) || app_slug="${APP_SLUG}"

if [[ -z "${app_slug}" ]]; then
  fail-message "APP_SLUG could not be parsed from env"
  exit 1
fi

read -r namespace deployment < <(kubectl get deployments -A --no-headers -l kots.io/app-slug="${app_slug}"  | awk '{print $1,$2}' | shuf -n1)

kubectl patch deployment -n "${namespace}" "${deployment}" --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/requests/memory", "value": "10Mi"}]'
kubectl patch deployment -n "${namespace}" "${deployment}" --type='json' -p='[{"op": "replace", "path": "/spec/template/spec/containers/0/resources/limits/memory", "value": "10Mi"}]'

debug-message "Mischief Managed!"
