#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# make sure the release directory is there
mkdir /home/replicant/release
chown replicant:replicant /home/replicant/release
chmod 755 /home/replicant/release

# get the current SDK version
sdk_version=$(curl -qsfL https://api.github.com/repos/replicatedhq/replicated-sdk/tags | jq -r '.[0] | .name')
agent variable set REPLICATED_SDK_VERSION ${sdk_version#?}
