#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# make sure the release directory is there
mkdir /home/replicant/release
chown replicant:replicant /home/replicant/release
chmod 755 /home/replicant/release
