#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

### Assure the tmux session exists
#
# In a test scenario Instuqt does not run the user shell for the
# challenge, which means the tmux session is never established. We
# need to session for the solve scripts for other challenges to 
# succeed, so let's create it here.
#

if ! tmux has-session -t shell ; then
  tmux new-session -d -s shell su - replicant
fi

# updat the chart version
tmux send-keys -t shell $'yq -i \'.version = "1.6.0"\' mastodon/Chart.yaml' ENTER

# add the SDK dependency
tmux send-keys -t shell $'yq -i \'.dependencies += { "name": "replicated", "repository": "oci://registry.replicated.com/library", "version": "0.0.1-alpha.15"}\' harbor/Chart.yaml' ENTER

# update dependencies
tmux send-keys -t shell 'helm dependency update mastodon'  ENTER

# re-package the chart
tmux send-keys -t shell 'helm package mastodon --destination release' ENTER
