#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
export HOME_DIR=/home/replicant

### Assure the tmux session exists
#
# In a test scenario Instuqt does not run the user shell for the
# challenge, which means the tmux session is never established. We
# need to session for the solve scripts for other challenges to 
# succeed, so let's create it here.
#

if ! tmux has-session -t shell ; then
  tmux new-session -d -s shell su - replicant
fi

# update the chart version
yq -i '.version = "0.2.0"' ${HOME_DIR}/slackernews/Chart.yaml

# add the SDK dependency
yq -i '.dependencies = []' ${HOME_DIR}/slackernews/Chart.yaml
yq -i ".dependencies += { \"name\": \"replicated\", \"repository\": \"oci://registry.replicated.com/library\", \"version\": \"$(agent variable get REPLICATED_SDK_VERSION)\"}" ${HOME_DIR}/slackernews/Chart.yaml

# re-package the chart
helm package --dependency-update ${HOME_DIR}/slackernews --destination ${HOME_DIR}/release

# make sure perms are good
chown -R replicant:replicant ${HOME_DIR}/slackernews ${HOME_DIR}/release
