#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# 
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

## don't require a password change since we just set it
chpasswd:
  expire: false

## add user `replicant`
users:
- default
- name: replicant
  gecos: "Replicated Lab Participant"
  groups:
  - users 
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  lock_passwd: true
 
## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## Install additional packages on first boot
packages:
- ca-certificates
- curl
- tmux
- jq

# install snaps on first boot
snap:
  commands:
  - snap install yq
  - snap install git-ubuntu --classic
  - snap install kubectl --classic
  - snap install helm --classic
  - snap install google-cloud-cli --classic

runcmd:
- chsh -s /usr/bin/bash replicant
- curl https://kots.io/install | bash
- |
  bash -c "(
    set -x
    export KREW_ROOT=/usr/local/libexec/krew
    export PATH=${KREW_ROOT}/bin:${PATH}
    curl -L https://krew.sh | bash
    curl -L https://krew.sh/ns | bash
    curl -L https://krew.sh/ctx | bash
    curl -L https://krew.sh/preflight | bash
    curl -L https://krew.sh/support-bundle | bash
    echo 'export KREW_ROOT=/usr/local/libexec/krew' >> /home/replicant/.profile
    echo 'export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"' >> /home/replicant/.profile
  )" 
- |
  bash -c "(
    set -x
    cd "$(mktemp -d)"
    wget -O replicated.tar.gz -q "$(curl -s https://api.github.com/repos/replicatedhq/replicated/releases/latest | yq '.assets[] | select(.browser_download_url | contains("linux_amd64")).browser_download_url')"
    tar -C /usr/local/bin -xzvf replicated.tar.gz replicated
  )"
- |
  bash -c "(
   curl -s https://api.github.com/repos/replicatedhq/sbctl/releases/latest \
      | jq -r '.assets[] | select ( .name == \"sbctl_linux_amd64.tar.gz\").browser_download_url' \
      | xargs curl --location \
      | tar -C /usr/local/bin -xzvf - sbctl \
    && chmod 755 /usr/local/bin/sbctl
  )"
