apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          env:
            - name: SECRET_ONE
              valueFrom:
                secretKeyRef:
                  name: secret-one
                  key: data
                  optional: true
            - name: SECRET_TWO
              valueFrom:
                secretKeyRef:
                  name: secret-two
                  key: data
                  optional: true
            - name: SECRET_THREE
              valueFrom:
                secretKeyRef:
                  name: secret-three
                  key: data
                  optional: true
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: html
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
            requests:
              memory: '32Mi'
              cpu: '100m'
      volumes:
        - name: config
          hostPath:
            path: /etc/lab10/
        - name: html
          configMap:
            name: nginx-html
        - name: secret-one
          secret:
            secretName: secret-one
            optional: true
        - name: secret-two
          secret:
            secretName: secret-two
            optional: true
        - name: secret-three
          secret:
            secretName: secret-three
            optional: true
