#!/bin/bash
set -exuo pipefail

for i in {1..3}; do
  # check for the file we created in the setup script
  ssh -oStrictHostKeyChecking=no kurl-node-${i} "stat /var/lib/chaos/bigfile" && echo "$?" >> /tmp/exit-status.txt || true
  if [[ $(cat /tmp/exit-status.txt) = 0 ]]; then
    fail-message "There seems to be one node still low on space"
    exit 1
  fi
done