#!/usr/bin/env bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

set -euxo pipefail
HOME_DIR=/home/replicant

export REPLICATED_API_TOKEN=$(agent variable get REPLICATED_API_TOKEN)
export REPLICATED_APP=$(agent variable get REPLICATED_APP)
app_slug=${REPLICATED_APP}
api_token=${REPLICATED_API_TOKEN}

# we know there's only one app, so just grab the first one
app_id=$(replicated app ls --output json | jq -r '.[0].id')

field_created=$(replicated api get /v3/app/2Ukd6bgLamUYOegqsNOPfjpfQVC/license-fields | jq '.[] | select ( .name == "member_count_max" )')

if [[ "${field_created}" == "true" ]] ; then
  fail-message 'Please create the "Max Member Count license field"'
  exit 1
fi

exit 0
