version: "3"
containers:
- name: shell
  image: gcr.io/kots-field-labs/shell:main
  shell: tmux new-session -A -s shell su - replicant
virtualmachines:
- name: cluster
  image: instruqt/k3s-v1-27-1
  shell: /bin/bash
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
