#!/bin/bash

echo "This is the solve script"


# curl https://kots.io/install | bash
# kubectl kots install hello-world \
#   --shared-password ${INSTRUQT_PARTICIPANT_ID} \
#   --namespace hello \
#   --no-port-forward

exit 0