#!/bin/bash


while ! agent variable get APP_SLUG; do
  debug-message "waiting for APP_SLUG to be set"
done

app_slug=$(agent variable get APP_SLUG)

if ! curl -LkSs "$HOSTNAME":8800; then
  fail-message "The Admin Console is not available on port 8800. Please expose the Application Installer admin console on port 8800."
  exit 1
fi

if [[ $(kubectl get deployments -A --no-headers -l kots.io/app-slug="${app_slug}"  | awk '{print $2}' | xargs shuf -n1 -e) = "No resources found." ]]; then
  fail-message "No deployments found for app-slug ${app_slug}. Please ensure that you've uploaded your license and the application is successfully deployed."
  exit 1
fi
