#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

if [[ -z "${APP_SLUG}" ]]; then
  fail-message "APP_SLUG is not set; please export APP_SLUG in the Workstation to configure the learning environment."
  exit 1
fi

if [[ -z "${CHANNEL}" ]]; then
  fail-message "CHANNEL is not set; please export CHANNEL in the Workstation to configure the learning environment."
  exit 1
fi

agent variable set APP_SLUG "${APP_SLUG}"
agent variable set CHANNEL "${CHANNEL}"

URL=$(agent variable get CLUSTER_URL)

if ! curl -LkSs "${URL}:8800"; then
  fail-message "The Admin Console is not available. please ensure you deployed the embedded cluster with KOTS."
  exit 1
fi

if [ ! -d /root/.kube ]; then
  # generate and fetch kubeconfig for cluster
  mkdir /root/.kube
  ssh kurl-node-1 "curl https://kurl.sh/latest/tasks.sh | SUDO_USER=root bash -s generate-admin-user"
  scp kurl-node-1:root.conf /root/.kube/config
fi

if [[ $(kubectl get deployments -A --no-headers -l kots.io/app-slug="${APP_SLUG}"  | awk '{print $2}' | xargs shuf -n1 -e) = "" ]]; then
  fail-message "No deployments found for app-slug ${APP_SLUG}. Please ensure that you've uploaded your license and the application is successfully deployed."
  exit 1
fi
