#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

if [[ -z "${APP_SLUG}" ]]; then
  fail-message "APP_SLUG is not set; please export APP_SLUG in the Workstation to configure the learning environment."
  exit 1
fi

if [[ -z "${CHANNEL}" ]]; then
  fail-message "CHANNEL is not set; please export CHANNEL in the Workstation to configure the learning environment."
  exit 1
fi

agent variable set APP_SLUG "${APP_SLUG}"
agent variable set CHANNEL "${CHANNEL}"
