apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: repl-db-provider
  labels:
    app: repl-db-provider
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repl-db-provider
  serviceName: repl-db-provider-service
  template:
    metadata:
      labels:
        app: repl-db-provider
    spec:
      containers:
      - env:
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        # create a db called "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        # create admin user with name "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: PGUSER
          value: "postgres"
        # use admin password from secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres
              key: DB_PASSWORD
        - name: POD_IP
          valueFrom: { fieldRef: { fieldPath: status.podIP } }
        ports:
        - name: postgresql
          containerPort: 5432  
        image: postgres:9.6
        name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pvc
      volumes:
      - name: postgres-pvc
        persistentVolumeClaim:
          claimName: postgres-pvc
  volumeClaimTemplates:
  - metadata:
      name: postgres-pvc
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi