apiVersion: v1
kind: Service
metadata:
  name: repl-db-provider-service
  labels:
    app: repl-db-provider-service
spec:
  type: ClusterIP
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
  selector:
    app: repl-db-provider
