#!/usr/bin/env bash
set -euxo pipefail
HOME_DIR=/home/replicant

# convenience library for Replicated lab lifecycle scripts
source /etc/profile.d/header.sh

# set up for the CLI and API
export REPLICATED_API_TOKEN=$(agent variable get REPLICATED_API_TOKEN)
export REPLICATED_APP=$(agent variable get REPLICATED_APP)
api_token=$(agent variable get REPLICATED_API_TOKEN)
app_slug=$(agent variable get REPLICATED_APP)

# add the URI to the support bundle spec
sed -i '/^    spec:/a \      uri: https://storage.googleapis.com/shared-lab-assets/closing-the-information-gap/slackernews/support-bundle.yaml' ${HOME_DIR}/slackernews/templates/troubleshoot/support-bundle.yaml

# bump the version number and package the chart
yq -i '.version = "0.4.1"' ${HOME_DIR}/slackernews/Chart.yaml
helm package ${HOME_DIR}/slackernews --destination ${HOME_DIR}/release

# release to the `Unstable` channel
replicated release create --promote Unstable --chart ${HOME_DIR}/release/slackernews-0.4.1.tgz --version 0.4.1  \
  --release-notes "Adds a support bundle spec to facilitate troubleshooting" \
  --app ${app_slug} --token ${api_token}

# get the sequence number for the release to promote
release_sequence=$(curl --header "Accept: application/json" --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].channels[] | select( .name == "Unstable" ) | .releaseSequence')

# promote to the `Beta` channel
replicated release promote ${release_sequence} Beta --version 0.4.1 \
  --release-notes "Adds a support bundle spec to facilitate troubleshooting" \
  --app ${app_slug} --token ${api_token}
 
# promote to the `Stable` channel
replicated release promote ${release_sequence} Stable --version 0.4.1 \
  --release-notes "Adds a support bundle spec to facilitate troubleshooting" \
  --app ${app_slug} --token ${api_token}

# upgrade to the new release
helm registry login registry.replicated.com \
  --username $(agent variable get CUSTOMER_EMAIL) \
  --password $(agent variable get REGISTRY_PASSWORD) 
helm upgrade --namespace slackernews slackernews \
  --kubeconfig ${HOME_DIR}/.kube/config \
  oci://registry.replicated.com/${app_slug}/slackernews

chown -R replicant ${HOME_DIR}/{slackernews,release}
