#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# save the session
tmux capture-pane -t airgap -S -10 -
SESSION=$(tmux save-buffer -)


NODE_READY=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes -o "jsonpath='{.items[0].status.conditions[?(@.type == \"Ready\")].status}'")
if [[ "${NODE_READY}" != "True" ]] ; then
  fail-message "Kubernetes cluster is not Ready, please make sure the install has completed"
  exit 1
fi

ADMIN_STATUS=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster curl -s -o /dev/null -w "%{http_code}" http://cluster:8800)
if [[ "${ADMIN_STATUS}" != "200" ]] ; then
  fail-message "Admin Console is not running, please make sure the install has completed"
  exit 1
fi

# check for disconnection
if ! grep -qE "Connection to cluster closed" <(echo ${SESSION}) ; then
  fail-message "Please make sure you disconnect from the cluster before continuing"
  exit 1
fi


exit 0
