#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# clear the tmux pane and scrollback to look like a fresh shell
tmux clear-history -t airgap 
tmux send-keys -t airgap clear ENTER

exit 0
