#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# get rid of the tarball
rm /home/replicant/*-replicated-labs-com.tar.gz

# clear the tmux pane and scrollback to look like a fresh shell
tmux clear-history -t airgap 
tmux send-keys clear ENTER

exit 0
