version: "3"
virtualmachines:
- name: vanilla
  image: kots-field-labs/ubuntu-2204-lts-200gb 
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: kurl-installed
  image: kots-field-labs/ubuntu-2204-lts-200gb 
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: kurl-ha-1
  image: kots-field-labs/ubuntu-2204-lts-200gb 
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: kurl-ha-2
  image: kots-field-labs/ubuntu-2204-lts-200gb 
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: kurl-ha-3
  image: kots-field-labs/ubuntu-2204-lts-200gb 
  shell: /bin/bash
  machine_type: n1-standard-8
  allow_external_ingress:
  - http
  - https
  - high-ports