#!/bin/bash 

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api 
do
    sleep 1 
done

# Local environment
echo "export PATH=${PATH}:${HOME}/.krew/bin" >> /root/.bashrc

# Enable bash completion for kubectl
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc

# Add kots kubectl plugin
curl -fsSL https://kots.io/install | bash

# Display PARTICIPANT_ID info for Vendor Portal
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/kots-field-labs/main/libs/header.sh
echo "show_credentials" >> /root/.bashrc

# Aliases
echo "alias l='ls -latFrh'" >> /root/.bash_aliases



echo "exiting track_scripts/setup-kubernetes-vm"
