#!/bin/bash 

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api 
do
    sleep 1 
done

# Enable bash completion for kubectl
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc

# Aliases
echo "alias l='ls -latFrh'" >> /root/.bash_aliases

# Display PARTICIPANT_ID info for Vendor Portal
echo "echo Credentials for https://vendor.replicated.com" >> /root/.bashrc
echo "echo Username: $INSTRUQT_PARTICIPANT_ID@replicated-labs.com" >> /root/.bashrc
echo "echo Password: $INSTRUQT_PARTICIPANT_ID" >> /root/.bashrc
