apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    kots.io/when: '{{repl not IsKurl }}'
spec:
  type: ClusterIP
  ports:
    - port: 80
  selector:
    app: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
  annotations:
    kots.io/when: '{{repl IsKurl }}'
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 8888
  selector:
    app: nginx
