#!/bin/bash
set -euxo pipefail

echo "Running challenge 03 setup script - Started.."
epoc_start=`date +%s`


# Download the application license file
#####get app token using vendor portal auth
#####install replicated cli


# done
epoc_end=`date +%s`
duration=$(($epoc_end - $epoc_start))
DURATION=`echo "DURATION: $(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."`
echo "challenge 03 setup script - Done ($DURATION)"

exit 0
