#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

HOME_DIR=/home/replicant

# get manifests to use for updating
git clone --depth 1 --filter=blob:none --sparse --branch instruqt-airgap-embedded https://github.com/replicatedhq/kots-field-labs
cd kots-field-labs
git sparse-checkout init
git sparse-checkout set instruqt/airgap-embedded
mv kots-field-labs/instruqt/airgap-embedded/vendor/manifests ${HOME_DIR}
rm -rf kots-field-labs

/bin/chown replicant:replicant ${HOME_DIR}/manifests
