#!/bin/sh

# clear the tmux pane and scrollback to look like a fresh shell
tmux clear-history -t airgap 
tmux send-keys clear ENTER

git clone --depth 1 --filter=blob:none --branch=instruqt-airgap-embedded --sparse https://github.com/replicatedhq/kots-field-labs.git
git sparse-checkoutt instruqt/airgap-embedded
