#!/bin/bash
# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

echo Install git
apt-get update
apt-get install -y git curl

echo Install replicated cli
curl -s https://api.github.com/repos/replicatedhq/replicated/releases/latest \
           | grep "browser_download_url.*$(uname | tr '[:upper:]' '[:lower:]')_amd64.tar.gz" \
           | cut -d : -f 2,3 \
           | tr -d \" \
           | cat <( echo -n "url") - \
           | curl -fsSL -K- \
           | tar xvz replicated
mv replicated /usr/local/bin/

echo Clone labs repo
git clone https://github.com/replicatedhq/kots-field-labs
cd kots-field-labs/labs/lab05-airgap