#!/bin/bash
# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail


# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done


iptables -A OUTPUT -p tcp -m string --string "kubernetes.io" --algo kmp -j REJECT
iptables -A OUTPUT -p tcp -m string --string "kurl.sh" --algo kmp -j REJECT
iptables -A OUTPUT -p tcp -m string --string "google.com" --algo kmp -j REJECT
iptables -A OUTPUT -p tcp -m string --string "replicated.app" --algo kmp -j REJECT
