#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# save the entire session to check user inputs and outputs
tmux capture-pane -t airgap -S -
SESSION=$(tmux save-buffer -)

# save the last _LINES_ lines to check inputs and outputs
LINES=10
HEIGHT=$(tmux list-panes -F "#{pane_height}")
SESSION=$(tmux capture-pane -t airgap -S $(expr $HEIGHT - $LINES) -p)
