#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# create the preflight file
cat <<HARBOR_BUNDLE > /home/replicant/slackernews-support-bundle.yaml
apiVersion: troubleshoot.sh/v1beta2
kind: SupportBundle
metadata:
  name: slackernews-support-bundle
spec:
  collectors:
    - logs:
        name: /app/slackernews/logs
        selector:
          - app=slackernews
  analyzers:
    - deploymentStatus:
        name: slackernews-frontend
        outcomes:
          - fail:
              when: "absent"
              message: |
                The Slackernews core component has not been deployed to this cluster. Please be sure to install the Slackernews
                application using its Helm chart.
          - fail:
              when: "< 1"
              message: |
                The Slackernews application is not currently running on this cluster. Please review the logs in this support
                bundle to locate any errors.
          - pass:
              message: |
                Ther Slackernews application is running on this cluster and ready for use.
HARBOR_BUNDLE


# NOTE - we used to collect a support bundle for the simplest support bundle
# definition, but the behvaior change so that explicitly settign collectors
# to [] leads to an error instead of a bundle with the default collectors
# having been collected
# kubectl support-bundle --namespace slackernews --interactive=false --kubeconfig /home/replicant/.kube/config /home/replicant/simplest-support-bundle.yaml
# collect the slackernews support bundles from the challenge
kubectl support-bundle --namespace slackernews --interactive=false --kubeconfig /home/replicant/.kube/config /home/replicant/slackernews-support-bundle.yaml

# make sure support bundle files are in the users home directory
mv support-bundle-*.tar.gz /home/replicant

# make sure all files have the correct ownership
chown -R replicant /home/replicant
