#!/bin/bash

service=$(agent variable get T3_SVC_NAME)
namespace=$(agent variable get T3_SVC_NS)
port=$(agent variable get T3_SVC_RANDPORT)

debug-message $service
debug-message $namespace

targetport=$(kubectl get service -n "${namespace}" "${service}" -o jsonpath='{.spec.ports[0].targetPort}')

debug-message $port
debug-message $targetport

if [[ "${targetport}" = "${port}" ]]; then
 fail-message "It looks like our service is still broken, check the hints for more information"
 exit 1
fi

fail-message "testing"
exit 1
