#!usr/bin/env bash
#WIP

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
 
agent variable set EXTERNAL_URL harbor.${HOSTNAME}.${_SANDBOX_ID}.instruqt.io

