#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the solve script"

exit 0
#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail


# collect the two support bundles from the challenge
kubectl support-bundle --interactive=false --kubeconfig /home/replicant/.kube/config /home/replicant/simplest-support-bundle.yaml
kubectl support-bundle --interactive=false --kubeconfig /home/replicant/.kube/config /home/replicant/harbor-support-bundle.yaml

# make sure support bundle files are in the users home directory
mv support-bundle-*.tar.gz /home/replicant

# make sure all files have the correct ownership
chown -R replicant /home/replicant

# verify looked at possible commands
if ! grep -qE 'replicated cluster versions+' <(echo ${SESSION}) ; then
  fail-message 'You can see what cluster distributions are supported with `replicated cluster versions`. Take a look!'
fi

# Verify simple cluster creation
# verify custom cluster creation
# List clusters
# remove clusters
# connect to cluster
# install app in cluster


