#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
source /etc/profile.d/header.sh

result=0

# check for release to Unstable
installed_chart=$(helm list -n slackernews -o yaml --kubeconfig /home/replicant/.kube/config | yq '.[0].chart')
if [[ ! "${installed_chart}" == "slackernews-0.2.0"  ]] ; then
  fail-message 'Please be sure to install the Slackernews Helm chart'
  let "result = result + 1"
fi

exit ${result}
