#!/usr/bin/env bash

# use our shared library (already downloaded by track setup)
source /etc/profile.d/header.sh

# Initialize check script
init_check_script

# Check that the Slackernews Helm chart is installed
check_helm_release "slackernews" "slackernews-0.2.0" \
    'Please be sure to install the Slackernews Helm chart'

# Finish check and exit with result
finish_check_script
