#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
source /etc/profile.d/header.sh

# get the customer id, since it's the password for the Helm installation
# and users like to copy/paste
api_token=$(get_api_token)
app_id=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].id')
customer_id=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customers" | jq -r '.customers[0].id')

# set the customer email so the user doesn't have to do it, also make it a paid license for the optics
customer_email="${INSTRUQT_PARTICIPANT_ID}@omozan.io"
updated_customer=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customer/${customer_id}" | \
  jq -c --arg appId "${app_id}" --arg email "${customer_email}" '.customer | {"app_id": $appId, "name": .name, "email": $email, "channel_id": .channels[0].id, "expires_at": .expiresAt, "type": "prod", "is_airgap_enabled": .airgap, "is_gitops_supported": .isGitopsSupported, "is_identity_service_supported": .isIdentityServiceSupported, "is_geoaxis_supported": .isGeoaxisSupported, "is_snapshot_supported": .isSnapshotSupported, "is_support_bundle_upload_enabled": .isSupportBundleUploadEnabled, "entitlementValues":[]}')

curl --location "https://api.replicated.com/vendor/v3/customer/${customer_id}" \
  --request PUT --header 'Accept: application/json' --header "Authorization: ${api_token}" \
  --header "Content-Type: application/json" \
  --data "${updated_customer}"
 
# get the registry password (which is the license id)
registry_password=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customer/${customer_id}/license-download" | \
  yq .spec.licenseID) 

# toggle the app to builders mode 
curl  --location "https://api.replicated.com/vendor/v3/app/${app_id}" \
  --request POST --header 'Accept: application/json' --header "Authorization: ${api_token}" \
  --header "Content-Type: application/json" \
  --data '{ "is_foundation": true }'

agent variable set APP_ID ${app_id}
agent variable set CUSTOMER_ID ${customer_id}
agent variable set CUSTOMER_EMAIL ${customer_email}
agent variable set REGISTRY_PASSWORD ${registry_password}
