#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euo pipefail
source /etc/profile.d/header.sh

# get the application slug for the chart URL
api_token=$(get_api_token)
app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')

# login to the registry  
registry_password=$(agent variable get REGISTRY_PASSWORD)
customer_email=$(agent variable get CUSTOMER_EMAIL)
echo "${registry_password}" | helm registry login registry.replicated.com \
  --username "${customer_email}" \
  --password-stdin 

# install the application
helm install --namespace slackernews --create-namespace slackernews \
  oci://registry.replicated.com/${app_slug}/slackernews \
  --set slackernews.domain=$(get_slackernews_domain) \
  --set service.type=NodePort \
  --kubeconfig /home/replicant/.kube/config