#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

results=0

# check whether the preflight has been created, we can assume that if it
# has the right number of outcomes they've probably done the work
if [[ ! $(yq '.spec.analyzers[] | select( .nodeResources.checkName | test("CPU")' /home/replicant/harbor-preflights.yaml) == "true" ]] ; then
  fail-message 'Please add the CPU resources preflight check to the Harbor preflights manifest'
  let "reasult = result + 1"
fi

if [[ ! $(yq '.spec.analyzers[] | select( .nodeResources.checkName | test("memory")' /home/replicant/harbor-preflights.yaml) == "true" ]] ; then
  fail-message 'Please add the memory preflight check to the Harbor preflights manifest'
  let "reasult = result + 1"
fi

if [[ ! $(yq '.spec.analyzers[] | select( .nodeResources.checkName | test("storage")' /home/replicant/harbor-preflights.yaml) == "true" ]] ; then
  fail-message 'Please add the storagmemorye preflight check to the Harbor preflights manifest'
  let "reasult = result + 1"
fi

return ${result}
