#!/usr/bin/env bash

# download and use our shared library with auto-download functionality
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/replicated-field-labs/refactor/crdant/builds-comprehensive-library/libs/header.sh
source /etc/profile.d/header.sh

# Initialize check script
init_check_script

# Check whether the CPU resources preflight has been added
check_condition '[[ $(yq ".spec.analyzers[] | select( .nodeResources.checkName | test(\"CPU\") ) | has(\"nodeResources\")" ${HOME_DIR}/slackernews-preflights.yaml) == "true" ]]' \
    'Please add the CPU resources preflight check to the Slackernews preflights manifest'

# Check whether the memory preflight has been added
check_condition '[[ $(yq ".spec.analyzers[] | select( .nodeResources.checkName | test(\"memory\") ) | has(\"nodeResources\")" ${HOME_DIR}/slackernews-preflights.yaml) == "true" ]]' \
    'Please add the memory preflight check to the Slackernews preflights manifest'

# Finish check and exit with result
finish_check_script
