#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

HOME_DIR=/home/replicant

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

# delete the worker nodes to constrain the cluster
kubectl delete node worker1 --kubeconfig /etc/rancher/k3s/k3s.yaml 
kubectl delete node worker2 --kubeconfig /etc/rancher/k3s/k3s.yaml 
