#!/bin/bash
set -euxo pipefail

echo "$INSTRUQT_USER_NAME started challenge $INSTRUQT_CHALLENGE_ID"
echo "Matriculating unmatriculated vectors..."

# patch a random service to use a random port

app_slug=$(agent variable get APP_SLUG) || app_slug="${APP_SLUG}"

if [[ -z "${app_slug}" ]]; then
  fail-message "APP_SLUG could not be parsed from env"
  exit 1
fi

service=$(kubectl get services -A -l kots.io/app-slug="${app_slug}" --no-headers | awk '{print $2}' | xargs shuf -n1 -e)
port=$(shuf -i 30000-32767 -n 1)

kubectl patch service "${service}" --type='json' -p="[{\"op\": \"replace\", \"path\": \"/spec/ports/0/port\", \"value\": \"${port}\"}]"
