apiVersion: kots.io/v1beta1
kind: Application
metadata:
  name: app-slug
spec:
  title: "Lab 1.9: Licenses"
  statusInformers:
    - deployment/nginx
  ports:
    - serviceName: "nginx"
      servicePort: 80
      localPort: 30888
      applicationUrl: "http://nginx"
  icon: data:image/png;base64,5e84879ce72cfd690148f840e62c16fb2709bddaa09763dba195eb137b798c49
