#!/bin/bash

# Create the nginx deployment
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      initContainers:
      - image: busybox
        name: coffee
        command:
        - sh
        - -c
        - sleeeep 10
      containers:
      - image: nginx
        name: nginx
EOF