#!/bin/bash
set -euxo pipefail

echo "Running track setup script - proxy-host"
epoc_start=`date +%s`

# Wait for the Instruqt host bootstrap to finish.
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# package install
yum install -y mlocate bind-utils

cat <<EOF>> ~/.ssh/config
Host isolated-host
  StrictHostKeyChecking no
EOF

#
LOCAL_HOST=`host proxy-host | grep for | awk '{print $1}'`
LOCAL_IP=`ifconfig eth0 | grep inet |grep -v inet6 | awk '{print $2}'`
PUB_HOST=$HOSTNAME.$_SANDBOX_ID.instruqt.io
PUB_IP=`host $PUB_HOST | grep has | awk '{print $4}'`
echo $LOCAL_IP $LOCAL_HOST >> /root/hosts
echo $PUB_IP $PUB_HOST >> /root/hosts

#
echo "net.ipv4.ip_forward = 1" | tee /etc/sysctl.d/99-ipforward.conf
echo 1 > /proc/sys/net/ipv4/ip_forward
sysctl -p
sysctl -a | grep ip_forward

# Deploy squid proxy
yum install -y squid
systemctl enable squid
systemctl start squid

# done
epoc_end=`date +%s`
duration=$(($epoc_end - $epoc_start))
DURATION=`echo "DURATION: $(($duration / 60)) minutes and $(($duration % 60)) seconds elapsed."`
echo "track setup script - proxy-host - Done ($DURATION)"

exit 0


