#!/usr/bin/env bash

# download and use our shared library with auto-download functionality
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/replicated-field-labs/refactor/crdant/builds-comprehensive-library/libs/header.sh
source /etc/profile.d/header.sh

# Initialize check script
init_check_script

# Check that required environment variables were exported to tmux session
check_tmux_var_export "shell" "REPLICATED_API_TOKEN" \
    'Please set the variable `$REPLICATED_API_TOKEN` so you will be able to use the `replicated` command in future steps'

check_tmux_var_export "shell" "REPLICATED_APP" \
    'Please set the variable `$REPLICATED_APP` so you will be working with the right application in future steps'

# Finish check and exit with result
finish_check_script
