#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
echo "Starting challenge 03 setup-kubernetes-vm"

set -eux

# expose nginx application
kubectl expose deployment nginx -n $(kubectl get pods -A -l app=nginx --no-headers | awk '{ print $1 }' ) --type=LoadBalancer --name=nginx-ingress --port=30888 --target-port=80


echo "exiting challenge 03 setup-kubernetes-vm"
exit 0
