#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

if [[ -z "${APP_SLUG}" ]]; then
  echo "APP_SLUG is not set; please export APP_SLUG to configure the learning environment."
  exit 1
fi

if [[ -z "${CHANNEL}" ]]; then
  echo "CHANNEL is not set; please export CHANNEL to configure the learning environment."
  exit 1
fi


# TODO: check to make sure that the application is deployed before continuing


# if all is well, export the app slug and channel to the user's .bashrc and continue
echo "export APP_SLUG=${APP_SLUG}" >> ~/.bashrc
echo "export CHANNEL=${CHANNEL}" >> ~/.bashrc
