#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

if [[ -z "${APP_SLUG}" ]]; then
  echo "APP_SLUG is not set; please export APP_SLUG to configure the learning environment."
  exit 1
fi

if [[ -z "${CHANNEL}" ]]; then
  echo "CHANNEL is not set; please export CHANNEL to configure the learning environment."
  exit 1
fi

if ! curl localhost:8800; then
  echo "The Admin Console is not available on port 8800. Please expose the Application Installer admin console on port 8800 via assignment step 3."
  exit 1
fi

# if all is well, export the app slug and channel to the user's .bashrc and continue
echo "export APP_SLUG=${APP_SLUG}" >> ~/.bashrc
echo "export CHANNEL=${CHANNEL}" >> ~/.bashrc
