#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

# kubectl kots install support-bundle \
#   --shared-password ${INSTRUQT_PARTICIPANT_ID} \
#   --namespace support \
#   --no-port-forward

# # Setup kotsadm - expose via loadbalancer
# kubectl expose deployment kotsadm -n $(kubectl get pods -A -l app=kotsadm --no-headers | awk '{ print $1 }' ) --type=LoadBalancer --name=kotsadm2 --port=8800 --target-port=3000

# exit 0
true
