#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

HOME_DIR=/home/replicant

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

# convenience library for Replicated lab lifecycle scripts
source /etc/profile.d/header.sh

# there's only one app created by the automation, so just grab the first in the list
access_token=$(get_api_token)
app_slug=$(get_app_slug)

agent variable set USERNAME $(get_username)
agent variable set PASSWORD $(get_password)
agent variable set REPLICATED_API_TOKEN ${access_token}
agent variable set REPLICATED_APP ${app_slug}
