#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

result=0

# check if the support bundle secret is present, which would indicate the upgrade was completed
analyzer_added=$(yq '.spec.analyzers[] | select( has("deploymentStatus") ) .deploymentStatus | select(.name == "harbor-core") | .name == "harbor-core"' /home/replicant/harbor-support-bundle.yaml)
if [[ "${analyzer_added}" == "false" ]] ; then
  fail-message 'Please check your support bundle definition to make sure you added the status check for Harbor Core'
  let "result = result + 1"
fi

# check whether the URI has been added to the spec
uri_added=$(yq '.spec.has("uri")')
if [[ "${collector_added}" == "uri" ]] ; then
  fail-message 'Please check your support bundle definition to make sure you added the uri for the updated bundle'
  let "result = result + 1"
fi

exit ${result}
