apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaky-app
  labels:
    app: flaky-app
spec:
  selector:
    matchLabels:
      app: flaky-app
  template:
    metadata:
      labels:
        app: flaky-app
    spec:
      containers:
        - name: flaky-app
          image: registry.replicated.com/REPLICATED_APP/prometheus-alerting:latest
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flaky-app
  labels:
    app: flaky-app
  annotations:
    kots.io/when: '{{repl (not IsKurl)}}'
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: http
  selector:
    app: flaky-app

---
apiVersion: v1
kind: Service
metadata:
  name: flaky-app
  labels:
    app: flaky-app
  annotations:
    kots.io/when: '{{repl IsKurl }}'
spec:
  type: NodePort
  ports:
    - port: 3000
      nodePort: 3000
      name: http
  selector:
    app: flaky-app
