#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
source /etc/profile.d/header.sh

HOME_DIR=/home/replicant

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

# get a token and the app slug
access_token=$(get_api_token)
app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${access_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')

# Display PARTICIPANT_ID info for Vendor Por
agent variable set USERNAME $(get_username)
agent variable set PASSWORD $(get_password)
agent variable set REPLICATED_API_TOKEN ${access_token}
agent variable set REPLICATED_APP ${app_slug}
