#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

### Assure the tmux session exists
#
# In a test scenario Instuqt does not run the user shell for the
# challenge, which means the tmux session is never established. We
# need to session for the solve scripts for other challenges to 
# succeed, so let's create it here.
#

if ! tmux has-session -t airgap ; then
  tmux new-session -d -s airgap su - replicant
fi

### Set the required environment variables

username="${INSTRUQT_PARTICIPANT_ID}@replicated-labs.com"
password=$(get_password)

login_request=$( jq -n -c --arg email "${username}" --arg password "${password}" '$ARGS.named' )
token=$(curl -s -H "Content-Type: application/json" --request POST -d "$login_request" https://id.replicated.com/v1/login | jq -r ".token")

i=0
while [[ "$token" == "null" && $i -lt 20 ]]
do
    sleep 2
    set +u
    token=$(curl -s -H "Content-Type: application/json" --request POST -d "$login_request" https://id.replicated.com/v1/login | jq -r ".token")
    echo $token
    set -u
    i=$((i+1))
done

UUID=$(cat /proc/sys/kernel/random/uuid)
api_token=$( jq -n -c --arg name "instruqt-${UUID}" --argjson read_only false '$ARGS.named' )
access_token=$(curl -s -H "Content-Type: application/json" -H "Authorization: $token" --request POST -d "$api_token" https://api.replicated.com/vendor/v1/user/token | jq -r ".access_token")
app_slug=$(curl -s -H "Content-Type: application/json" -H "Authorization: ${access_token}" https://api.replicated.com/vendor/v3/apps | jq --raw-output ".apps [] | select(.name | test(\".*${INSTRUQT_PARTICIPANT_ID}.*\")).slug")

tmux send-keys -t airgap export SPACE REPLICATED_API_TOKEN=${access_token} ENTER
tmux send-keys -t airgap export SPACE REPLICATED_APP=${app_slug} ENTER
