#!/bin/bash
set -exuo pipefail

rm -rf /root/support-bundle*
rm -rf /root/solution*

curl https://spooky.academy/support_bundles/troubleshoot_4_support_bundle.tar.gz -o support-bundle.tar.gz

cd /opt/
tee quiz.go << EOF
package main

import (
	"fmt"
	"os"
)

func main() {
	fmt.Println("Which of the following do you think is the cause of the problem:")
	fmt.Println("A) Local host does not resolve")
	fmt.Println("B) The container runtime is broken")
	fmt.Println("C) The disk on the node is full")
	fmt.Println("D) Quantum time calculations backfired in the flux capacitor")

	fmt.Printf("%s: ", "Type a letter")
	var answer string
	_, err := fmt.Scanln(&answer)
	if err != nil {
		fmt.Println("oops, something seems to have gone wrong, try re-running me")
		fmt.Println(err)
	}
	if answer == "c" || answer == "C" {
		fmt.Println("congratulations!")
		os.Create("/tmp/challenge_ok")
	} else {
		fmt.Println("oops! that doesn't appear to be the correct answer!")
	}
}
EOF
go build ./quiz.go
mv quiz /usr/bin/
rm quiz.go
