#!/bin/bash
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails.
#

deployment=frontend
namespace=default

debug-message $deployment
debug-message $namespace

replicas=$(kubectl -n "${namespace}" get deployment "${deployment}" -o jsonpath='{.spec.replicas}')

debug-message $replicas

if [[ "$replicas" = "0" ]]; then
  fail-message "It looks like our application is still down, see the hints for how to proceed."
  exit 1
fi
