#!/bin/bash

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# Wait for the Kubernetes API server to become available
while ! curl --silent --fail --output /dev/null http://localhost:8001/api
do
    sleep 1
done

# Enable bash completion for kubectl
echo "source /usr/share/bash-completion/bash_completion" >> /root/.bashrc
echo "complete -F __start_kubectl k" >> /root/.bashrc

# Add kots kubectl plugin
curl -fsSL https://kots.io/install | bash

debug-message "Starting practical application track $INSTRUQT_TRACK_ID for $INSTRUQT_USER_NAME on $(date)"
debug-message "Sandbox $_SANDBOX_ID"
debug-message "Hostname $HOSTNAME"

agent variable set SANDBOX_ID "$_SANDBOX_ID"
agent variable set HOSTNAME "$HOSTNAME"
agent variable set ADMIN_CONSOLE_PORT 8800
agent variable set HOST_URL "https://$HOSTNAME.$_SANDBOX_ID.instruqt.io"

