#!/bin/bash
set -exuo pipefail


set +u
until [[ -n $deployment  ]] ; do
  read -r namespace deployment < <(kubectl get deployments -A --no-headers -l app=kotsadm  | awk '{print $1,$2}' | shuf -n1)
done
set -u

# try to use curl to resolve the kubernetes api, grab stderr to check later
kubectl -n "${namespace}" exec -it -c kotsadm "${deployment}" -- curl kubernetes.default.svc.cluster.local 2> /opt/test.txt

# check saved stderr from curl
if [[ $(grep "exit code 6" /opt/test.txt) ]]; then
    fail-message "It looks like dns is still broken, check the hints for help"
    exit 1
fi
