#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

REPLICANT_HOME=/home/replicant

if ! find ${REPLICANT_HOME} -name "installing-in-an-air-gapped-environment-*-unstable.tar.gz" > /dev/null 2>&1 ; then
  fail-message "You do not appear to have started downloading the bundle, please start the download before continuing"
  exit 1
fi
