#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# ssh-keyscan -H cluster >> /root/known-hosts
REMOTE_FILES=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster ls)

if ! grep -q "installing-in-an-air-gapped-environment" <(echo ${REMOTE_FILES}) ; then
  fail-message "Please make sure to copy the kURL bundle to the air-gapped host."
  exit 1
fi

exit 0
