#!/bin/sh

REPLICANT_HOME=/home/replicant

if ! find ${REPLICANT_HOME} -name "*-replicated-labs-com-development.tar.gz" > /dev/null 2>&1 ; then
  fail-message "Please make sure you've set your API token and run save_lab_setup"
  exit 1
fi

exit 0
