#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# save the session
# tmux capture-pane -t airgap -S -
# SESSION=$(tmux save-buffer -)

# echo "Checking if bundle download is complete..."
# while ! echo "${SESSION}" | tail -1 | grep "replicant" ;
# do
#   sleep 5
#   tmux capture-pane -t airgap -S -
#   SESSION=$(tmux save-buffer -)
# done

REPLICANT_HOME=/home/replicant
scp -o StrictHostKeyChecking=no -i ${REPLICANT_HOME}/.ssh/id_ed25519 ${REPLICANT_HOME}/*.tar.gz replicant@cluster:
