version: "3"
containers:
- name: shell
  image: gcr.io/kots-field-labs/replicated-cli
  shell: tmux new-session -A -s shell su - replicant
virtualmachines:
- name: kubernetes-vm
  image: instruqt/k3s-v1-27-1
  shell: /bin/bash
  machine_type: n1-standard-2
  allow_external_ingress:
  - http
  - https
  - high-ports 
