#!/usr/bin/env bash
#
# This script runs when the platform cleanup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

set -euxo pipefail

# convenience library for Replicated lab lifecycle scripts
source /etc/profile.d/header.sh

# get he API token for this script to use
api_token=$(get_api_token)
cluster_name=$(agent variable get USERNAME)

replicated cluster rm $(replicated cluster ls --output json --token ${api_token} | jq --arg name ${cluster_name}  -r '.[] | select ( .name == $name ) | .id') --token ${api_token}
