#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

cat <<HARBOR_SUPPORT_BUNDLE > /home/replicant/slackernews/templates/troubelshoot/support-bundle.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-support-bundle
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    app.kubernetes.io/component: support-bundle
    troubleshoot.sh/kind: support-bundle
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
  support-bundle-spec: |
    apiVersion: troubleshoot.sh/v1beta2
    kind: SupportBundle
    metadata:
      name: slackernews-support-bundle
    spec:
      collectors:
        - logs:
            name: /app/slackernews/logs
            selector:
                - app.kubernetes.io/name=slackernews
        - configMap:
            namespace: default
            selector:
            - app.kubernetes.io/name=slackernews
        - configMap:
            name: slackernews-core
            namespace: default
            key: EXT_ENDPOINT
            includeValue: true
        - secret:
            name: slackernewse-core
            namespace: default
            key: tls.crt
            includeValue: true
        - secret:
            name: slackernews-ingress
            key: ca.crt
            includeVale: true
        - secret:
            name: slackernews-ingress
            key: tls.crt
            includeVale: true
        - secret:
            namespace: default
            selector:
            - app.kubernetes.io/name=slackernews
      analyzers:
        - deploymentStatus:
            name: slackernews-core
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Slackernews core workload has not been deployed to this cluster. Please be sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Slackernews core workload is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    Ther Slackernews core workload is running on this cluster and ready for use.
        - clusterVersion:
            outcomes:
              - fail:
                  when: "< 1.19.x"
                  message: |-
                    Your Kubernets cluster is running a version of Kubernetes that is not supported by the Slackernews container
                    registry and your installation will not succeed. Please upgrade your cluster or install to a different
                    cluster running at least Kubernetes 1.19, ideally version 1.24.0 or later.
                  uri: https://github.com/bitnami/charts/blob/main/bitnami/slackernews/README.md
              - warn:
                  when: "< 1.24.0"
                  message: |-
                    Your Kubernetes cluster is running a version of Kubernetes that is not longer supported by the Kubernetes
                    community. If you are receiving extended support from your Kubernetes provider you may be able to ignore
                    this warning. If not, we recomend that you upgrade your cluster to at least version 1.24.0.
                  uri: https://kubernetes.io
              - pass:
                  message: Your cluster is running a version of Kubernetes that is supported by the Slackernews container registry.
        - nodeResources:
            checkName: Cluster CPU resources are sufficient to install and run Slackernews
            outcomes:
              - fail:
                  when: "sum(cpuAllocatable) < 2"
                  message: |-
                    Slackernews requires a minimum of 2 CPU cores in order to run, and runs best with
                    at least 4 cores. Your current cluster has less than 2 CPU cores available to Kubernetes
                    workloads. Please increase cluster capacity or install into a different cluster.
                  uri: https://goslackernews.io/docs/2.8.0/install-config/installation-prereqs/
              - warn:
                  when: "sum(cpuAllocatable) < 4"
                  message: |-
                    Slackernews runs best with a minimum of 4 CPU cores. Your current cluster has less
                    than 4 CPU cores available to run workloads. For the best experience, consider
                    increasing cluster capacity or installing into a different cluster.
                  uri: https://goslackernews.io/docs/2.8.0/install-config/installation-prereqs/
              - pass:
                  message: Your cluster has sufficient CPU resources available to run Slackernews
        - nodeResources:
            checkName: Cluster memory is sufficient to install and run Slackernews
            outcomes:
              - fail:
                  when: "sum(memoryAllocatable) < 4G"
                  message: |-
                    Slackernews requires a minimum of 4 GB of memory in order to run, and runs best with
                    at least 8 GB. Your current cluster has less than 4 GB available to Kubernetes
                    workloads. Please increase cluster capacity or install into a different cluster.
                  uri: https://goslackernews.io/docs/2.8.0/install-config/installation-prereqs/
              - warn:
                  when: "sum(memoryAllocatable) < 8Gi"
                  message: |-
                    Slackernews runs best with a minimum of 8 GB of memory. Your current cluster has less
                    than 8 GB of memory available to run workloads. For the best experience, consider
                    increasing cluster capacity or installing into a different cluster.
                  uri: https://goslackernews.io/docs/2.8.0/install-config/installation-prereqs/
              - pass:
                  message: Your cluster has sufficient memory available to run Slackernews
        - deploymentStatus:
            name: slackernews-jobservice
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Slackernews job service has not been deployed to this cluster. Please sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Slackernews job service is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    Ther Slackernews job service is running on this cluster and ready for use.
        - deploymentStatus:
            name: slackernews-portal
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Slackernews portal workload has not been deployed to this cluster. Please sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Slackernews portal workload is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    Ther Slackernews portal workload is running on this cluster and ready for use.
        - deploymentStatus:
            name: slackernews-registry
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Slackernews registry workload has not been deployed to this cluster. Please sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Slackernews registry workload is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    Ther Slackernews registry workload is running on this cluster and ready for use.
        - statefulsetStatus:
            name: slackernews-postgresql
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Slackernews database has not been deployed to this cluster. Please sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Slackernews database is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    Ther Slackernews database is running on this cluster and ready for use.
        - statefulsetStatus:
            name: slackernews-redis-master
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Slackernews cache has not been deployed to this cluster. Please sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Slackernews cache is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    Ther Slackernews cache is running on this cluster and ready for use.
        - statefulsetStatus:
            name: slackernews-trivy
            namespace: default
            outcomes:
              - fail:
                  when: "absent"
                  message: |
                    The Trivy iamge scanner has not been deployed to this cluster. Please sure to install the Slackernews registry application using its Helm chart.
              - fail:
                  when: "< 1"
                  message: |
                    The Trivy image scanner is not currently running on this cluster. Please review the logs in this support bundle to locate any errors.
              - pass:
                  message: |
                    The Trivy image scanner is running on this cluster and ready for use.
HARBOR_SUPPORT_BUNDLE

yq -i '.version = "0.4.0"' /home/replicant/slackernews/Chart.yaml
helm package /home/replicant/slackernews --destination /home/replicant/release
chown -R replicant /home/replicant/slackernews /home/replicant/release
