---
#cloud-config

# This is the user-data configuration file for cloud-init. By default this sets
# 
# up an initial user called "ubuntu" with password "ubuntu", which must be
# changed at first login. However, many additional actions can be initiated on
# first boot from this file. The cloud-init documentation has more details:
#
# https://cloudinit.readthedocs.io/
#
# Some additional examples are provided in comments below the default
# configuration.

## don't require a password change since we just set it
chpasswd:
  expire: false

## Update apt database and upgrade packages on first boot
package_update: true
package_upgrade: true

## Install additional packages on first boot
packages:
- ca-certificates
- curl

users:
- default
- name: replicant
  gecos: "Replicate Lab User"
  groups:
  - users 
  - adm 
  - sudo
  - ssher
  sudo: "ALL=(ALL) NOPASSWD:ALL"
  lock_passwd: true

groups:
- ssher

write_files:
- path: /etc/ssh/sshd_config.d/01-hardening.conf
  content: |
    # enable eed25519 key
    HostKey /etc/ssh/ssh_host_ed25519_key

    # restrict supported key exchange, cipher, and MAC algorithms
    KexAlgorithms curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,diffie-hellman-group-exchange-sha256
    Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
    MACs hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
    HostKeyAlgorithms ssh-ed25519,ssh-ed25519-cert-v01@openssh.com,sk-ssh-ed25519@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,rsa-sha2-256,rsa-sha2-512,rsa-sha2-256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com

    # restrict authentication mechanism
    PasswordAuthentication yes
    ChallengeResponseAuthentication no
    PubkeyAuthentication yes
  permissions: '0644'
  owner: root:root

runcmd:
- curl https://kurl.sh/k3s | bash
- usermod -a -G ssher replicant 
- echo "# limit who can use SSH\nAllowGroups ssher" > /etc/ssh/sshd_config.d/02-limit-to-ssher.conf
