#!/usr/bin/env bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# convenience library for Replicated lab lifecycle scripts
source /etc/profile.d/header.sh

## set variables for use in instructions
# there's only one app created by the automation, so just grab the first in the list
access_token=$(get_api_token)
app_slug=$(curl --header 'Accept: application/json' --header "Authorization: ${access_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].slug')

agent variable set USERNAME $(get_username)
agent variable set PASSWORD $(get_password)
agent variable set REPLICATED_APP ${app_slug}

exit 0
