#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is challenge 01 setup script"

# kubernetes k3s is running
kubectl get nodes > /root/getnodes.out

exit 0
