version: "3"
virtualmachines:
- name: jumpbox
  image: kots-field-labs/airgap-jumpbox
  shell: tmux new-session -A -s airgap su - replicant
  machine_type: n1-standard-2
  version: "2"
  allow_external_ingress:
  - high-ports
containers:
- name: airgap
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
gcp_projects:
- name: airgap
  services:
  - compute.googleapis.com
  roles:
  - roles/compute.admin
  - roles/iam.serviceAccountUser
