version: "3"
containers:
- name: jumpbox
  image: gcr.io/kots-field-labs/replicated-cli
  shell: /bin/bash
  memory: 256
gcp_projects:
- name: airgap
  services:
  - compute.googleapis.com
  roles:
  - roles/compute.networkAdmin
  - roles/compute.securityAdmin
