#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
HOME_DIR=/home/replicant
source /etc/profile/header.sh

# save the entire session to check user inputs and outputs
tmux capture-pane -t shell -S -
SESSION=$(tmux save-buffer -)

# check for disconnection
if ! grep -qE 'THIS=[A-Za-z "]+' <(echo ${SESSION}) ; then
  fail-message 'Please try it out by setting the environment variable `$THIS`'
  exit 1
fi

