#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euo pipefail
HOME_DIR=/home/replicant
source /etc/profile.d/header.sh

### Assure the tmux session exists
#
# In a test scenario Instuqt does not run the user shell for the
# challenge, which means the tmux session is never established. We
# need to session for the solve scripts for other challenges to 
# succeed, so let's create it here.
#
if ! tmux has-session -t shell ; then
  tmux new-session -d -s shell su - replicant
fi

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

mkdir -p ${HOME_DIR}/release
chown replicant:replicant ${HOME_DIR}/release
chmod 755 ${HOME_DIR}/release

