#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

HOME_DIR=/home/replicant

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

# convenience library for Replicated lab lifecycle scripts
source /etc/profile.d/header.sh

agent variable set USERNAME $(get_username)
agent variable set PASSWORD $(get_password)
agent variable set REPLICATED_API_TOKEN $(get_api_token)
