#!/bin/sh
#
# This script runs when the platform check the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

echo "This is the check script"

# Disabled till we figure out how to get a license using the API.
# /usr/local/bin/kubectl get all | grep -v kotsadm | grep nginx

