#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#
echo "Starting challenge 02 setup-kubernetes-vm"

#set -eux

# set up troubleshoot deployment blocker files
# not creating the config.txt so it can be created during execrise
mkdir -p /etc/support
touch /etc/support/restraining-bolt.txt
touch /etc/support/secretkey.txt
touch /etc/support/config.txt
chmod 400 /etc/support/restraining-bolt.txt
chmod 400 /etc/support/secretkey.txt


# pre-install the kots app
kubectl kots install support-cli-$INSTRUQT_PARTICIPANT_ID --name support-cli-$INSTRUQT_PARTICIPANT_ID --namespace default --shared-password $INSTRUQT_PARTICIPANT_ID --no-port-forward 

# expose kotsadm
kubectl expose deployment kotsadm -n $(kubectl get pods -A -l app=kotsadm --no-headers | awk '{ print $1 }' ) --type=LoadBalancer --name=kotsadm-ingress --port=8800 --target-port=3000


echo "exiting challenge 02 setup-kubernetes-vm"
exit 0
