#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
source /etc/profile.d/header.sh


# login to the registry
helm registry login registry.replicated.com \
  --username $(agent variable get USERNAME) \ 
  --password $(agent variable get REGISTRY_PASSWORD) 

# install the application
helm install mastodon oci://registry.replicated.com/$(agent variable get REPLICATED_APP)/stable/mastodon --kubeconfig /home/replicated/.kube/config --wait
