#!/usr/bin/env bash

# download and use our shared library with auto-download functionality
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/replicated-field-labs/refactor/crdant/builds-comprehensive-library/libs/header.sh
source /etc/profile.d/header.sh

# Initialize check script
init_check_script

# check for release to Unstable
installed_chart=$(helm list -n slackernews -o yaml --kubeconfig ${HOME_DIR}/.kube/config | yq '.[0].chart')
check_condition '[[ "${installed_chart}" == "slackernews-0.3.0" ]]' \
    'Please be sure to install the Slackernews Helm chart'

# Finish check and exit with result
finish_check_script
