#!/usr/bin/env bash

# download and use our shared library with auto-download functionality
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/replicated-field-labs/refactor/crdant/builds-comprehensive-library/libs/header.sh
source /etc/profile.d/header.sh

# Initialize setup script with proper error handling
init_setup_script

app_slug=$(agent variable get REPLICATED_APP)

helm registry login $(agent variable get REGISTRY_HOST) --username $(agent variable get REGISTRY_USERNAME)  --password $(agent variable get REGISTRY_PASSWORD)

helm install --namespace slackernews --create-namespace \
  slackernews --version 0.3.0 \
  oci://$(agent variable get REGISTRY_HOST)/${app_slug}/slackernews \
  --set nginx.service.type=NodePort --set nginx.service.nodePort.port=30443 \
  --set slackernews.domain=cluster-30443-${INSTRUQT_PARTICIPANT_ID}.env.play.instruqt.com \
  --kubeconfig ${HOME_DIR}/.kube/config
