#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# simple SSH client setup so we can SSH to/from the shell

cat <<EOF >> "$HOME/.ssh/config"
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
EOF

# assure an RSA key for Dropbear
ssh-keygen -t rsa -f /etc/dropbear/dropbear_rsa_host_key -N ''

# change the cluster URI
yq -i '.clusters[0].cluster.server = "https://kubernetes-vm:6443"' /home/replicant/.kube/config
chown -R replicant /home/replicant/.kube

# Display PARTICIPANT_ID info for Vendor Portal
echo "echo Credentials for https://vendor.replicated.com" >> /home/replicant/.bashrc
echo "echo Username: $INSTRUQT_PARTICIPANT_ID@replicated-labs.com" >> /home/replicant/.bashrc
echo "echo Password: $INSTRUQT_PARTICIPANT_ID" >> /home/replicant/.bashrc
