#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail
source /etc/profile.d/header.sh

result=0

# check for release to Unstable
api_token=$(get_api_token)
customer_email=${INSTRUQT_PARTICIPANT_ID}@geeglo.io
#
# get the app id in order to work with the customer
app_id=$(curl --header "Accept: application/json" --header "Authorization: ${api_token}" https://api.replicated.com/vendor/v3/apps | jq -r '.apps[0].id')

# create the new customer and keep track of the ID
new_customer=$(curl --header 'Accept: application/json' --header "Authorization: ${api_token}" "https://api.replicated.com/vendor/v3/app/${app_id}/customers" | jq -r '.customers[] | select( .name == "Geeglo" )')
if [[ -z "${new_customer}" ]] ; then
  fail-message $'Please remember to create the customer Geeglo'
  let "result = result + 1"
fi

if [[ -f /home/replicant/.config/helm/registry/config.json ]] ; then
  registry_auth_username=$(jq -r '.auths."registry.replicated.com".auth | @base64d | split(":")[0]'  /home/replicant/.config/helm/registry/config.json)
  if [[ ! "${registry_auth_username}" == "${customer_email}"  ]] ; then
    fail-message $'Please log into the Replicated registry as the customer you created'
    let "result = result + 1"
  fi
else
  fail-message $'Please log into the Replicated registry as the customer you created'
  let "result = result + 1"
fi

exit ${result}
