#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

### Assure the tmux session exists
#
# In a test scenario Instuqt does not run the user shell for the
# challenge, which means the tmux session is never established. We
# need to session for the solve scripts for other challenges to 
# succeed, so let's create it here.
#

if ! tmux has-session -t shell ; then
  tmux new-session -d -s shell su - replicant
fi

# clear the tmux pane and scrollback to look like a fresh shell
tmux clear-history -t shell 
tmux send-keys -t shell q ENTER
tmux send-keys -t shell clear ENTER

exit 0
