#!/usr/bin/env bash

# use our shared library (already downloaded by track setup)
source /etc/profile.d/header.sh

# Initialize check script
init_check_script

# Check for LTS channel existence
check_channel_exists "LTS" \
    'Please be sure to create the channel `LTS` for releases with long-term support available'

# Check for release and promotions to multiple channels with version 0.2.0
check_channel_promotions "0.2.0" "Unstable,Beta,Stable"

# Finish check and exit with result
finish_check_script
