#!/bin/bash

deployment=$(agent variable get T2_DEP_NAME)
namespace=$(agent variable get T2_DEP_NS)

unavailableReplicas=$(kubectl get deployment -n "${namespace}" "${deployment}" -o jsonpath='{.status.unavailableReplicas}')

if [[ ! "$unavailableReplicas" = "" ]]; then
    fail-message "It looks like our application is still broken, please check the hints for more information"
    exit 1
fi

if [[ ! -f /root/solution.yaml ]]; then
  fail-message "solution.yaml not found in /root/, please create the file and try again"
  exit 1
fi

kind=$(yq -r '.kind' /root/solution.yaml)

if [[ ! "$kind" = "Deployment" ]]; then
  fail-message "your solution doesn't look correct, you appear to have saved a resource that we weren't expecting"
  exit 1
fi

limits=$(yq '.spec.template.spec.containers[0].resources.limits.memory' solution.yaml -r)

if [[ "$limits" = "5M" ]]; then
  fail-message "it looks like your solution is incorrect"
fi

exit 1
