#!/bin/bash

set -euxo
rm -rf /root/support-bundle* || true
rm /root/solution.txt || true

curl https://cre-training-assets.s3.us-west-1.amazonaws.com/troubleshoot_2_support_bundle.tar.gz -o support-bundle.tar.gz
