#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

cp /root/.bashrc /home/replicant
chown replicant:replicant /home/replicant/.bashrc
echo "cd /home/replicant" >> /root/.bashrc
echo "su - replicant" >> /root/.bashrc
