#!/bin/sh
#
# This script runs when the platform solve the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

yq -i '.spec.template.spec.containers[0].resources.requests.cpu = "100m"' /home/replicant/manifests/deployment.yaml
yq -i '.spec.template.spec.containers[0].resources.requests.memory = "64Mi"' /home/replicant/manifests/deployment.yaml

