version: "3"
virtualmachines:
  - name: kurl-vm
    image: ubuntu-os-cloud/ubuntu-2204-lts
    machine_type: n1-standard-4
    shell: /bin/bash -l
    allow_external_ingress:
        - http
        - https
        - high-ports
