version: "3"
virtualmachines:
- name: loadbalancer
  image: ubuntu-os-cloud/ubuntu-2204-lts
  shell: /bin/bash -l
  machine_type: n1-standard-2
  allow_external_ingress:
      - http
      - https
      - high-ports
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  ports: [80]
  shell: /bin/bash
gcp_projects:
- name: kurl
  services:
  - compute.googleapis.com
  - container.googleapis.com
  roles:
  - roles/compute.admin
  - roles/container.admin
  - roles/iam.serviceAccountUser
