version: "3"
# virtualmachines:
# - name: kurl-1
#   image: ubuntu-os-cloud/ubuntu-2204-lts
#   machine_type: n1-standard-8
#   shell: /bin/bash -l
#   allow_external_ingress:
#       - http
#       - https
#       - high-ports
# - name: kurl-2
#   image: ubuntu-os-cloud/ubuntu-2204-lts
#   machine_type: n1-standard-8
#   shell: /bin/bash -l
#   allow_external_ingress:
#       - http
#       - https
#       - high-ports
# - name: kurl-3
#   image: ubuntu-os-cloud/ubuntu-2204-lts
#   machine_type: n1-standard-8
#   shell: /bin/bash -l
#   allow_external_ingress:
#       - http
#       - https
#       - high-ports
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  ports: [80]
  shell: /bin/bash
- name: kurl-node-1
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  cmd: ssh kurl-node-1 --ignore-host-key-checks
- name: kurl-node-2
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  cmd: ssh kurl-node-2 --ignore-host-key-checks
- name: kurl-node-3
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  cmd: ssh kurl-node-3 --ignore-host-key-checks
gcp_projects:
- name: kurl
  services:
  - compute.googleapis.com
  - container.googleapis.com
  roles:
  - roles/compute.admin
  - roles/container.admin
  - roles/iam.serviceAccountUser
