#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

# simple SSH client setup so we can SSH to/from the shell

cat <<EOF >> "$HOME/.ssh/config"
Host *
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    PubkeyAcceptedKeyTypes +ssh-rsa
EOF

while ! ssh shell true; do
  echo "Waiting for container SSH to be available..."
  sleep 1
done

cat <<'SAVE_SCRIPT' >> sharelog.sh
#!/bin/bash 
tail -f kurl.log | ssh shell "cat > /home/replicant/kurl.log" 2> ssh.err

SAVE_SCRIPT

chmod a+x sharelog.sh

curl https://kurl.sh/short-demo-$INSTRUQT_PARTICIPANT_ID > install.sh
chmod +x install.sh
nohup sudo ./install.sh > kurl.log 2> kurl.err < /dev/null & disown
nohup ./sharelog.sh > tail.log 2> tail.err < /dev/null & disown

exit 0