#!/bin/bash

# Wait for the Instruqt host bootstrap to finish
until [ -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
    sleep 1
done

{
  echo "export SHELL=bash"
  echo "source /usr/share/bash-completion/bash_completion"
  echo "complete -F __start_kubectl k"
} >> /root/.bashrc


# install kubectl
curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
  && chmod +x ./kubectl \
  && mv ./kubectl /usr/local/bin/kubectl

# Add kots plugin
# curl -fsSL https://kots.io/install | bash

# install sbctl
curl -LO https://github.com/replicatedhq/sbctl/releases/latest/download/sbctl_linux_amd64.tar.gz \
  && tar -xzvf sbctl_linux_amd64.tar.gz  -C /tmp sbctl \
  && cp /tmp/sbctl /usr/local/bin/sbctl \
  && rm sbctl_linux_amd64.tar.gz

# install support-bundle
curl -LO https://github.com/replicatedhq/troubleshoot/releases/latest/download/support-bundle_linux_amd64.tar.gz \
  && tar -xvzf support-bundle_linux_amd64.tar.gz -C /tmp support-bundle \
  && cp /tmp/support-bundle /usr/local/bin/kubectl-support_bundle \
  && rm support-bundle_linux_amd64.tar.gz

debug-message "Starting practical application track with kurl $INSTRUQT_TRACK_ID for $INSTRUQT_USER_NAME on $(date)"
debug-message "Sandbox $_SANDBOX_ID"
debug-message "Hostname $HOSTNAME"

agent variable set SANDBOX_ID "$_SANDBOX_ID"
agent variable set HOSTNAME "$HOSTNAME"
agent variable set ADMIN_CONSOLE_PORT 8800
agent variable set HOST_URL "https://$HOSTNAME.$_SANDBOX_ID.instruqt.io"

### authenticate to gcloud
mkdir -p /root/.config/gcloud
echo "$INSTRUQT_GCP_PROJECT_KURL_SERVICE_ACCOUNT_KEY" | base64 -d > /root/.config/gcloud/credentials.json

# Activate the service account
gcloud auth activate-service-account --key-file /root/.config/gcloud/credentials.json

# Set our project
gcloud config set project "$INSTRUQT_GCP_PROJECT_KURL_PROJECT_ID"

# add a hard disk for Rook
gcloud disks create rook-disk-"$HOSTNAME" \
  --size=200GB \
  --zone=europe-west1-b

gcloud compute instances attach-disk "$HOSTNAME" \
 --disk rook-disk-"$HOSTNAME" \
  --zone=europe-west1-b

