#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
# set -euxo pipefail
set -x

# Wait for Instruqt bootstrap to be complete
while [ ! -f /opt/instruqt/bootstrap/host-bootstrap-completed ]
do
  echo "Waiting for Instruqt to finish booting the VM"
  sleep 1
done

### authenticate to gcloud
mkdir -p /root/.config/gcloud

debug-message "$(printenv)"

echo $INSTRUQT_GCP_PROJECT_KURL_SERVICE_ACCOUNT_KEY | base64 -d > /root/.config/gcloud/credentials.json

# Activate the service account
gcloud auth activate-service-account --key-file /root/.config/gcloud/credentials.json

# Set our project
gcloud config set project $INSTRUQT_GCP_PROJECT_KURL_PROJECT_ID
