#!/usr/bin/env bash
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# convenience library for Replicated lab lifecycle scripts
source /etc/profile.d/header.sh

agent variable set USERNAME $(get_username)
agent variable set PASSWORD $(get_password)

exit 0
