#!/bin/sh
#
# This script runs when the platform setup the challenge.
#
# The platform determines if the script was successful using the exit code of this
# script. If the exit code is not 0, the script fails. 
#

# clear the tmux pane and scrollback to look like a fresh shell
tmux clear-history -t airgap 
tmux send-keys clear ENTER

# prepare for SSH
HOME_DIR=/home/replicant

### copy the participant SSH key to the user `replicant`
if [ -d /opt/instruqt/ssh/participant-ssh-key ]; then
  SSH_DIR=${HOME_DIR}/.ssh
  mkdir -p "${SSH_DIR}"
  /bin/chmod 0700 "${SSH_DIR}"
  cat /opt/instruqt/ssh/participant-ssh-key/public_key >> ${SSH_DIR}/authorized_keys
  cat /opt/instruqt/ssh/participant-ssh-key/public_key  > ${SSH_DIR}/id_rsa.pub
  cat /opt/instruqt/ssh/participant-ssh-key/private_key > ${SSH_DIR}/id_rsa
  # ssh-keyscan -H cluster >> ${SSH_DIR}/known_hosts
  /bin/chmod 0600 ${SSH_DIR}/*
  /bin/chown -R replicant ${SSH_DIR}
fi

exit 0
