#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

# short circuit if testing
set +x
TEST_RUN=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster "[[ ! -f /tmp/.test-solve ]] || cat /tmp/.test-solve")
if [[ "${TEST_RUN}" == "True" ]] ; then
  exit 0
fi
set -x

DEPLOYMENT_READY=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster kubectl --kubeconfig /etc/kubernetes/admin.conf get deployments -o "jsonpath='{.items[?(@.metadata.name == \"kuard\")].status.conditions[?(@.type == \"Available\")].status}'")
if [[ "${DEPLOYMENT_READY}" != "True" ]] ; then
  fail-message "Upgraded applicaation not available, please make sure the install has completed"
  exit 1
fi

DEPLOYMENT_TAG=$(ssh -o StrictHostKeyChecking=no -i /home/replicant/.ssh/id_ed25519 replicant@cluster kubectl --kubeconfig /etc/kubernetes/admin.conf get deployments -o "jsonpath='{.items[?(@.metadata.name == \"kuard\")].spec.template.spec.containers[?(@.name == \"kuard\")].image}'" | cut -d: -f 2)
if [[ "${DEPLOYMENT_TAG}" != "green" ]] ; then
  fail-message "Running application is not the correct version, please make sure you uploaded the new bundle"
  exit 1
fi

exit 0
