version: "3"
containers:
- name: shell
  image: gcr.io/kots-field-labs/shell
virtualmachines:
- name: node
  image: kots-field-labs/future-cluster-node
  shell: tmux new-session -A -s shell su - replicant
virtualmachines:
- name: cluster
  image: instruqt/k3s-v1-29-0
  shell: /bin/bash
  machine_type: n1-standard-1
