version: "3"
containers:
- name: shell
  image: gcr.io/kots-field-labs/shell:main
  shell: tmux new-session -A -s shell su - replicant
virtualmachines:
- name: node
  image: kots-field-labs/future-node
  shell: /bin/bash
  machine_type: n2d-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
