#!/bin/bash 

CYAN='\033[0;36m'
NC='\033[0m' # No Color

# change the cluster URI
yq -i '.clusters[0].cluster.server = "https://application:6443"' /home/replicant/.kube/config
chown -R replicant /home/replicant/.kube


# Display PARTICIPANT_ID info for Vendor Portal
echo "export INSTRUQT_PARTICIPANT_ID=${INSTRUQT_PARTICIPANT_ID}" >> /home/replicant/.bashrc
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/kots-field-labs/main/libs/header.sh
echo "show_credentials" >> /home/replicant/.bashrc