#!/usr/bin/env bash

# This set line ensures that all failures will cause the script to error and exit
set -euxo pipefail

REPLICANT_HOME=/home/replicant

if ! find ${REPLICANT_HOME} -name "installing-in-an-air-gapped-environment-*-unstable.tar.gz" > /dev/null 2>&1 ; then
  fail-message "Please make sure you've set your API token and run save_lab_setup"
  exit 1
fi

exit 0
