#!/usr/bin/env bash

# download and use our shared library with auto-download functionality
curl -s -o /etc/profile.d/header.sh https://raw.githubusercontent.com/replicatedhq/replicated-field-labs/refactor/crdant/builds-comprehensive-library/libs/header.sh
source /etc/profile.d/header.sh

# Initialize check script
init_check_script

# Check whether the preflight has been created with the right number of outcomes
check_condition '[[ $(yq ".spec.analyzers[0].clusterVersion.outcomes | length" ${HOME_DIR}/slackernews-preflights.yaml) -eq 3 ]]' \
    'Please check your preflights to make sure you have added the Kubernetes version check'

# Finish check and exit with result
finish_check_script
